export const frameworks = [
  { value: "react", label: "React" },
  { value: "vue", label: "Vue" },
  { value: "angular", label: "Angular" },
  { value: "svelte", label: "Svelte" },
  { value: "solid", label: "Solid" },
]

export const databases = [
  { value: "postgres", label: "PostgreSQL" },
  { value: "mysql", label: "MySQL" },
  { value: "mongodb", label: "MongoDB" },
  { value: "redis", label: "Redis" },
  { value: "sqlite", label: "SQLite" },
]

export const languages = [
  { value: "javascript", label: "JavaScript" },
  { value: "typescript", label: "TypeScript" },
  { value: "python", label: "Python" },
  { value: "rust", label: "Rust" },
  { value: "go", label: "Go" },
]

export const clouds = [
  { value: "aws", label: "AWS" },
  { value: "gcp", label: "Google Cloud" },
  { value: "azure", label: "Azure" },
  { value: "digitalocean", label: "DigitalOcean" },
  { value: "heroku", label: "Heroku" },
]

export const tools = [
  { value: "vscode", label: "VS Code" },
  { value: "vim", label: "Vim" },
  { value: "intellij", label: "IntelliJ" },
  { value: "sublime", label: "Sublime Text" },
  { value: "atom", label: "Atom" },
]

export const features = [
  { id: "comments", label: "Comments" },
  { id: "authentication", label: "Authentication" },
  { id: "api", label: "API Integration" },
  { id: "database", label: "Database" },
  { id: "testing", label: "Testing" },
]

export const projectTypes = [
  { value: "web", label: "Web Application" },
  { value: "mobile", label: "Mobile Application" },
  { value: "desktop", label: "Desktop Application" },
]

export const settingsOptions = [
  { id: "public", label: "Public Repository" },
  { id: "opensource", label: "Open Source" },
]

export const themeOptions = [
  { value: "light", label: "Light" },
  { value: "dark", label: "Dark" },
  { value: "system", label: "System" },
]

export const libraries = [
  { value: "react", label: "React" },
  { value: "redux", label: "Redux" },
  { value: "mobx", label: "MobX" },
  { value: "recoil", label: "Recoil" },
  { value: "zustand", label: "Zustand" },
  { value: "jotai", label: "Jotai" },
  { value: "valtio", label: "Valtio" },
  { value: "xstate", label: "XState" },
  { value: "react-query", label: "React Query" },
  { value: "swr", label: "SWR" },
  { value: "apollo-client", label: "Apollo Client" },
  { value: "urql", label: "URQL" },
  { value: "relay", label: "Relay" },
  { value: "react-router", label: "React Router" },
  { value: "wouter", label: "Wouter" },
  { value: "react-location", label: "React Location" },
  { value: "formik", label: "Formik" },
  { value: "react-hook-form", label: "React Hook Form" },
  { value: "react-final-form", label: "React Final Form" },
  { value: "yup", label: "Yup" },
  { value: "zod", label: "Zod" },
  { value: "joi", label: "Joi" },
  { value: "ajv", label: "Ajv" },
  { value: "react-select", label: "React Select" },
  { value: "downshift", label: "Downshift" },
  { value: "react-datepicker", label: "React Datepicker" },
  { value: "date-fns", label: "date-fns" },
  { value: "dayjs", label: "Day.js" },
  { value: "moment", label: "Moment.js" },
  { value: "luxon", label: "Luxon" },
  { value: "react-dnd", label: "React DnD" },
  { value: "react-beautiful-dnd", label: "React Beautiful DnD" },
  { value: "dnd-kit", label: "DnD Kit" },
  { value: "react-dropzone", label: "React Dropzone" },
  { value: "react-pdf", label: "React PDF" },
  { value: "react-window", label: "React Window" },
  { value: "react-virtualized", label: "React Virtualized" },
  { value: "react-infinite-scroll", label: "React Infinite Scroll" },
  { value: "react-waypoint", label: "React Waypoint" },
  { value: "react-intersection-observer", label: "React Intersection Observer" },
  { value: "framer-motion", label: "Framer Motion" },
  { value: "react-spring", label: "React Spring" },
  { value: "react-transition-group", label: "React Transition Group" },
  { value: "react-move", label: "React Move" },
  { value: "recharts", label: "Recharts" },
  { value: "victory", label: "Victory" },
  { value: "visx", label: "visx" },
  { value: "nivo", label: "Nivo" },
  { value: "react-three-fiber", label: "React Three Fiber" },
  { value: "drei", label: "Drei" },
  { value: "react-map-gl", label: "React Map GL" },
  { value: "leaflet", label: "Leaflet" },
  { value: "deck.gl", label: "deck.gl" },
  { value: "react-table", label: "React Table" },
  { value: "tanstack-table", label: "TanStack Table" },
  { value: "ag-grid", label: "AG Grid" },
  { value: "material-table", label: "Material Table" },
  { value: "react-data-grid", label: "React Data Grid" },
  { value: "react-virtualized-tree", label: "React Virtualized Tree" },
  { value: "react-sortable-tree", label: "React Sortable Tree" },
  { value: "react-treebeard", label: "React Treebeard" },
  { value: "react-calendar", label: "React Calendar" },
  { value: "react-big-calendar", label: "React Big Calendar" },
  { value: "fullcalendar", label: "FullCalendar" },
  { value: "react-color", label: "React Color" },
  { value: "react-colorful", label: "React Colorful" },
  { value: "react-input-mask", label: "React Input Mask" },
  { value: "react-number-format", label: "React Number Format" },
  { value: "react-text-mask", label: "React Text Mask" },
  { value: "react-markdown", label: "React Markdown" },
  { value: "react-syntax-highlighter", label: "React Syntax Highlighter" },
  { value: "prismjs", label: "Prism.js" },
  { value: "highlight.js", label: "highlight.js" },
  { value: "react-player", label: "React Player" },
  { value: "video.js", label: "Video.js" },
  { value: "react-use-gesture", label: "React Use Gesture" },
  { value: "use-gesture", label: "Use Gesture" },
  { value: "react-hook-form", label: "React Hook Form" },
  { value: "react-query", label: "React Query" },
  { value: "swr", label: "SWR" },
  { value: "react-error-boundary", label: "React Error Boundary" },
  { value: "react-helmet", label: "React Helmet" },
  { value: "react-snap", label: "React Snap" },
  { value: "react-snapshot", label: "React Snapshot" },
  { value: "react-loadable", label: "React Loadable" },
  { value: "loadable-components", label: "Loadable Components" },
  { value: "react-lazy-load", label: "React Lazy Load" },
  { value: "react-visibility-sensor", label: "React Visibility Sensor" },
  { value: "react-window", label: "React Window" },
  { value: "react-virtualized", label: "React Virtualized" },
  { value: "react-virtuoso", label: "React Virtuoso" },
  { value: "react-infinite-scroll-component", label: "React Infinite Scroll Component" },
  { value: "react-infinite-scroller", label: "React Infinite Scroller" },
  { value: "react-waypoint", label: "React Waypoint" },
  { value: "react-intersection-observer", label: "React Intersection Observer" },
  { value: "react-responsive", label: "React Responsive" },
  { value: "react-device-detect", label: "React Device Detect" },
  { value: "react-use-measure", label: "React Use Measure" },
  { value: "react-measure", label: "React Measure" },
  { value: "react-sizeme", label: "React Size Me" },
  { value: "react-resize-detector", label: "React Resize Detector" },
  { value: "react-window-size", label: "React Window Size" },
  { value: "react-use-size", label: "React Use Size" },
  { value: "react-div-100vh", label: "React Div 100vh" },
  { value: "react-div-100vh", label: "React Div 100vh" },
  { value: "react-custom-scrollbars", label: "React Custom Scrollbars" },
  { value: "react-perfect-scrollbar", label: "React Perfect Scrollbar" },
  { value: "react-scrollbar", label: "React Scrollbar" },
  { value: "react-scroll", label: "React Scroll" },
  { value: "react-scrollspy", label: "React Scrollspy" },
  { value: "react-visibility-sensor", label: "React Visibility Sensor" },
  { value: "react-waypoint", label: "React Waypoint" },
  { value: "react-intersection-observer", label: "React Intersection Observer" },
  { value: "react-lazyload", label: "React Lazyload" },
  { value: "react-lazy-load-image-component", label: "React Lazy Load Image Component" },
  { value: "react-progressive-image", label: "React Progressive Image" },
  { value: "react-progressive-image-loading", label: "React Progressive Image Loading" },
  { value: "react-image", label: "React Image" },
  { value: "react-images", label: "React Images" },
  { value: "react-photo-gallery", label: "React Photo Gallery" },
  { value: "react-image-gallery", label: "React Image Gallery" },
  { value: "react-image-lightbox", label: "React Image Lightbox" },
  { value: "react-modal", label: "React Modal" },
  { value: "react-responsive-modal", label: "React Responsive Modal" },
  { value: "react-modal-image", label: "React Modal Image" },
  { value: "react-images-viewer", label: "React Images Viewer" },
  { value: "react-medium-image-zoom", label: "React Medium Image Zoom" },
  { value: "react-image-magnify", label: "React Image Magnify" },
  { value: "react-zoom-pan-pinch", label: "React Zoom Pan Pinch" },
  { value: "react-easy-crop", label: "React Easy Crop" },
  { value: "react-image-crop", label: "React Image Crop" },
  { value: "react-avatar-editor", label: "React Avatar Editor" },
  { value: "react-avatar", label: "React Avatar" },
  { value: "react-gravatar", label: "React Gravatar" },
  { value: "react-identicons", label: "React Identicons" },
  { value: "react-icons", label: "React Icons" },
  { value: "react-feather", label: "React Feather" },
  { value: "react-fontawesome", label: "React FontAwesome" },
  { value: "react-line-awesome", label: "React Line Awesome" },
  { value: "react-eva-icons", label: "React Eva Icons" },
  { value: "react-hero-icons", label: "React Hero Icons" },
  { value: "react-bootstrap-icons", label: "React Bootstrap Icons" },
  { value: "react-remix-icon", label: "React Remix Icon" },
  { value: "react-boxicons", label: "React Boxicons" },
  { value: "react-icons-kit", label: "React Icons Kit" },
  { value: "react-icomoon", label: "React IcoMoon" },
  { value: "react-ionicons", label: "React Ionicons" },
  { value: "react-evil-icons", label: "React Evil Icons" },
  { value: "react-typicons", label: "React Typicons" },
  { value: "react-themify-icons", label: "React Themify Icons" },
  { value: "react-octicons", label: "React Octicons" },
  { value: "react-material-icons", label: "React Material Icons" },
  { value: "react-weather-icons", label: "React Weather Icons" },
  { value: "react-flag-icon-css", label: "React Flag Icon CSS" },
  { value: "react-country-flag", label: "React Country Flag" },
  { value: "react-world-flags", label: "React World Flags" },
  { value: "react-emoji-render", label: "React Emoji Render" },
  { value: "react-emoji", label: "React Emoji" },
  { value: "react-emojione", label: "React EmojiOne" },
  { value: "react-twemoji", label: "React Twemoji" },
  { value: "react-emoji-mart", label: "React Emoji Mart" },
  { value: "react-loading", label: "React Loading" },
  { value: "react-spinners", label: "React Spinners" },
  { value: "react-loader-spinner", label: "React Loader Spinner" },
  { value: "react-content-loader", label: "React Content Loader" },
  { value: "react-placeholder", label: "React Placeholder" },
  { value: "react-loading-skeleton", label: "React Loading Skeleton" },
  { value: "react-shimmer", label: "React Shimmer" },
  { value: "react-loading-overlay", label: "React Loading Overlay" },
  { value: "react-block-ui", label: "React Block UI" },
  { value: "react-spinkit", label: "React Spinkit" },
  { value: "react-epic-spinners", label: "React Epic Spinners" },
  { value: "react-progress", label: "React Progress" },
  { value: "react-circular-progressbar", label: "React Circular Progressbar" },
  { value: "react-sweet-progress", label: "React Sweet Progress" },
  { value: "react-top-loading-bar", label: "React Top Loading Bar" },
  { value: "react-toastify", label: "React Toastify" },
  { value: "react-hot-toast", label: "React Hot Toast" },
  { value: "react-toast-notifications", label: "React Toast Notifications" },
  { value: "react-notifications", label: "React Notifications" },
  { value: "react-notification-system", label: "React Notification System" },
  { value: "react-notification", label: "React Notification" },
  { value: "react-notifications-component", label: "React Notifications Component" },
  { value: "react-alert", label: "React Alert" },
  { value: "react-confirm-alert", label: "React Confirm Alert" },
  { value: "react-confirm", label: "React Confirm" },
  { value: "react-confirm-box", label: "React Confirm Box" },
  { value: "react-tooltip", label: "React Tooltip" },
  { value: "react-tippy", label: "React Tippy" },
  { value: "react-popper-tooltip", label: "React Popper Tooltip" },
  { value: "react-tooltips", label: "React Tooltips" },
  { value: "react-portal-tooltip", label: "React Portal Tooltip" },
  { value: "react-portal", label: "React Portal" },
  { value: "react-portal-overlay", label: "React Portal Overlay" },
  { value: "react-overlays", label: "React Overlays" },
  { value: "react-overlay", label: "React Overlay" },
  { value: "react-aria-modal", label: "React Aria Modal" },
  { value: "react-modal", label: "React Modal" },
  { value: "react-responsive-modal", label: "React Responsive Modal" },
  { value: "react-modal-dialog", label: "React Modal Dialog" },
  { value: "react-modal-box", label: "React Modal Box" },
]